### ISSUE TITLE
Python Style is ALL WRONG

### ISSUE THREAD

**Issue by tdhopper** [kevinsheth/pureNumbers#1]
One thing you should take a look at is Python Style guidelines. For better or worse, a big giveaway that someone isn't a pyhton programmer is they don't use [snake case](https://en.wikipedia.org/wiki/Snake_case), e.g. using `getRoastedCoffee` instead `get_roasted_coffee`. 

You'll here people refer to [PEP8](https://www.python.org/dev/peps/pep-0008/). This provides the guidelines for Python code written for the core language's codebase, but it's commonly applied to python code more broadly. 

[Google's style guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md) is great and is basically what I try to follow.

Recently I've been looking at [black](https://black.readthedocs.io/en/stable/) which is a code formatter that automatically restyles and reformats your code.

**Comment by kevinsheth** [comment]
I was actually thinking about this today. Does snake case apply to variables only or also functions?

**Comment by tdhopper** [comment]
Variables too. Here's the section from Google: https://github.com/google/styleguide/blob/gh-pages/pyguide.md#316-naming
